#!/bin/bash
#
# Generate jobs.txt for slurm/parallel_train.sh — one runner arg-string per line.
#
# Usage:
#   bash slurm/make_jobs.sh
#   bash slurm/make_jobs.sh --models kot_main
#   bash slurm/make_jobs.sh --out jobs/jobs_quick.txt
#
#   sbatch --export=ALL,JOBS_FILE=jobs/jobs_quick.txt,MAX_PARALLEL=16 slurm/parallel_train.sh
#
# @STAMP@ is replaced at sweep start so a jobs file still names dirs for when it ran.
# Unique --run-dir per line so parallel jobs cannot overwrite each other.
# Several arms on one line share a run dir and seed, which is what makes a matched ablation.
set -euo pipefail

STAMP="@STAMP@"   # resolved by parallel_train.sh at run time
ROOT="cache/training"
OUT="jobs.txt"
# Reported runs train on every cell like the baselines; the val slice is for hyperparameter choice, not for fitting the reported model.
FULL_DATA="--set val_holdout_from_training=false"
# `kot` is the model group: kot + kot_noanchor + kot_nodyn.
MODELS="kot"
REAL_LAMBDAS=(1 2)
SYN_LAMBDAS=(1 10)

while [ $# -gt 0 ]; do
  case "$1" in
    --models) MODELS="$2"; shift 2 ;;
    --out)    OUT="$2";    shift 2 ;;
    -h|--help) sed -n '2,14p' "$0"; exit 0 ;;
    *) echo "unknown flag: $1" >&2; exit 1 ;;
  esac
done

lam_tag() { printf "lam%03d" "$1"; }

{
  echo "# Generated by slurm/make_jobs.sh on $(date +%Y-%m-%d) -- do not hand-edit run dirs."
  echo "#"
  echo "# Submit:  sbatch --export=ALL,JOBS_FILE=${OUT},MAX_PARALLEL=16 slurm/parallel_train.sh"
  echo "#"
  echo "# --models ${MODELS}: the runner writes each arm to <run-dir>/<model>/, so arms"
  echo "# stay matched on run and seed. Regenerate with --models kot_main for the"
  echo "# headline arm alone (3x faster, but the ablation panels stay blocked)."
  echo "#"
  echo "# @STAMP@ is replaced by parallel_train.sh with the sweep start time."
  echo "#"
  echo "# Real-data lines carry ${FULL_DATA}: these are the reported runs and"
  echo "# train on every cell. The dev-only validation holdout belongs to the search"
  echo "# (slurm/make_sweep_jobs.sh), not here."
  echo "# Inspect afterwards:  ls -d ${ROOT}/run_<stamp>_*   (stamp is printed in the slurm log)"
  echo
  echo "# ============================ real CITE-seq ============================"
  echo "# velocity backend x dataset x lambda_dyn"
  for pair in "bmmc:bmmc_cite_retained:bmmc_cite_regvelo" "pbmc:pbmc_retained:pbmc_regvelo"; do
    IFS=: read -r tissue scvelo regvelo <<< "${pair}"
    for lam in "${REAL_LAMBDAS[@]}"; do
      echo "--datasets ${scvelo} --models ${MODELS} ${FULL_DATA} --set lambda_dyn=${lam} --run-dir ${ROOT}/run_${STAMP}_${tissue}_scvelo_$(lam_tag "${lam}")"
      echo "--datasets ${regvelo} --models ${MODELS} ${FULL_DATA} --set lambda_dyn=${lam} --run-dir ${ROOT}/run_${STAMP}_${tissue}_regvelo_$(lam_tag "${lam}")"
    done
  done
  echo
  echo "# ========================= staged synthetic ============================"
  echo "# stage x lambda_dyn, mean scale only (log is misspecified and collapses phi)"
  for stage in oracle clean branch; do
    for lam in "${SYN_LAMBDAS[@]}"; do
      echo "--datasets synthetic_linked_ode --models ${MODELS} --stage ${stage} --scale mean --set lambda_dyn=${lam} --run-dir ${ROOT}/run_${STAMP}_syn_${stage}_mean_$(lam_tag "${lam}")"
    done
  done
} > "${OUT}"

# Count lines starting with --; the header comment also contains "--run-dir".
n_jobs=$(grep -c '^--' "${OUT}")
n_dirs=$(grep '^--' "${OUT}" | grep -o '\-\-run-dir [^ ]*' | sort -u | wc -l)
echo "Wrote ${OUT}: ${n_jobs} jobs, ${n_dirs} unique run-dirs"
[ "${n_jobs}" -eq "${n_dirs}" ] || { echo "ERROR: run-dir collision — jobs would overwrite each other" >&2; exit 1; }
echo "Submit:  sbatch --export=ALL,JOBS_FILE=${OUT},MAX_PARALLEL=16 slurm/parallel_train.sh"
