#!/bin/bash
#
# Generate a hyperparameter-sweep jobs file for slurm/parallel_train.sh.
#
# This is NOT slurm/make_jobs.sh: that one generates the fixed paper runs (all three
# KOT arms, 5 seeds, canonical weights). This one generates a SEARCH — one arm
# (kot_main), fewer seeds, one run-dir per config, and --no-predictions on every line
# so parallel jobs cannot collide on the global data/predictions/ HDF5 path.
#
# Usage:
#   bash slurm/make_sweep_jobs.sh --tier a                    # 2-D core: lambda_dyn x kappa prior
#   bash slurm/make_sweep_jobs.sh --tier b --lam 300          # 1-D scans at the tier-A winner
#   bash slurm/make_sweep_jobs.sh --tier c --lam 300          # curriculum: warmup / phases / lr
#   bash slurm/make_sweep_jobs.sh --tier a --datasets pbmc_retained --seeds 42   # quick probe
#
#   sbatch --export=ALL,JOBS_FILE=jobs_sweep_a.txt,MAX_PARALLEL=8 slurm/parallel_train.sh
#
# Read the result with:
#   python tools/collect_run_diagnostics.py --runs 'cache/training/run_<stamp>_*' --aggregate
#
# Seeds come from the dataset's `seeds:` list in config/training.yaml (5 on the real
# datasets) unless --seeds overrides them. Since the search then uses every configured
# seed, confirm the winning config on FRESH seeds afterwards --
#   --seeds 11,17,21,33,77   (already the tail of the synthetic seed list)
# so the headline number is not the argmin over the same seed noise the search ranked on.
set -euo pipefail

STAMP="@STAMP@"          # resolved by parallel_train.sh at submit time
ROOT="cache/training"
TIER=""
OUT=""
SEEDS=""                 # empty = use the dataset's own `seeds:` from config/training.yaml
MODELS="kot_main"        # one arm during search; the 3-arm group is for the paper runs
DATASETS="pbmc_retained pbmc_regvelo bmmc_cite_retained bmmc_cite_regvelo"
LAM=""                   # tier b/c: the lambda_dyn chosen from tier a

while [ $# -gt 0 ]; do
  case "$1" in
    --tier)     TIER="$2";     shift 2 ;;
    --out)      OUT="$2";      shift 2 ;;
    --seeds)    SEEDS="$2";    shift 2 ;;
    --models)   MODELS="$2";   shift 2 ;;
    --datasets) DATASETS="${2//,/ }"; shift 2 ;;
    --lam)      LAM="$2";      shift 2 ;;
    -h|--help)  sed -n '2,22p' "$0"; exit 0 ;;
    *) echo "unknown flag: $1" >&2; exit 1 ;;
  esac
done

[ -n "${TIER}" ] || { echo "--tier a|b|c is required" >&2; exit 1; }
OUT="${OUT:-jobs_sweep_${TIER}.txt}"
case "${TIER}" in
  b|c) [ -n "${LAM}" ] || { echo "--tier ${TIER} needs --lam <lambda_dyn from tier a>" >&2; exit 1; } ;;
esac

# Short filesystem-safe tag for a value: 5.0e-4 -> 5p0e-4, true -> true, 0.05 -> 0p05.
tag() { echo "${1//./p}"; }

# One job line. `job <dsdir-tag> <dataset> <extra --set flags...>`
emit() {
  local cfgtag="$1"; shift
  local dataset="$1"; shift
  local short="${dataset/_retained/_scv}"; short="${short/_regvelo/_rgv}"
  short="${short/bmmc_cite/bmmc}"
  local seed_flag=""
  [ -n "${SEEDS}" ] && seed_flag="--seeds ${SEEDS} "
  echo "--datasets ${dataset} --models ${MODELS} ${seed_flag}--no-predictions $* --run-dir ${ROOT}/run_${STAMP}_sw${TIER}_${short}_${cfgtag}"
}

{
  echo "# Sweep tier ${TIER} -- generated by slurm/make_sweep_jobs.sh on $(date +%Y-%m-%d)."
  echo "# seeds=${SEEDS:-from config/training.yaml}  models=${MODELS}  datasets=${DATASETS}${LAM:+  lambda_dyn=${LAM}}"
  echo "#"
  echo "# Submit:  sbatch --export=ALL,JOBS_FILE=${OUT},MAX_PARALLEL=8 slurm/parallel_train.sh"
  echo "# Collect: python tools/collect_run_diagnostics.py --runs 'cache/training/run_<stamp>_sw${TIER}_*' --aggregate"
  echo

  case "${TIER}" in

    a)
      # Tier A: the two coupled knobs. lambda_dyn=1 is dropped -- the 20260823 sweep
      # showed it is statistically indistinguishable from kot_nodyn on every real
      # dataset (0.35-0.48 FOSCTTM, seed sd up to 0.22), so it is a dead cell.
      # kappa railed to 0.03-0.07 against a 0.693 prior target at lambda_kappa_prior
      # 0.01, so the prior strength and the target are both scanned.
      echo "# ===== lambda_dyn x kappa-prior (2-D core) ====="
      for ds in ${DATASETS}; do
        for lam in 10 30 100 300 1000; do
          for kp in "0:0.6931471805599453" "0.01:0.6931471805599453" \
                    "0.1:0.6931471805599453" "0.1:0.05" "1.0:0.05"; do
            IFS=: read -r lkp target <<< "${kp}"
            emit "lam$(tag "${lam}")_lkp$(tag "${lkp}")_kt$(tag "${target:0:4}")" "${ds}" \
                 "--set lambda_dyn=${lam} --set lambda_kappa_prior=${lkp} --set kot_kappa_prior=${target}"
          done
        done
      done
      ;;

    b)
      # Tier B: 1-D scans holding lambda_dyn at the tier-A winner. Run length first --
      # best_align_epoch clustered at 430-500 of a 500 cap in every 20260823 run, so
      # training is being cut off while still improving.
      echo "# ===== run length ====="
      for ds in ${DATASETS}; do
        for ep in 500 1000 2000; do
          for pat in 100 300; do
            emit "ep${ep}_pat${pat}" "${ds}" \
                 "--set lambda_dyn=${LAM} --set n_epochs=${ep} --set early_stopping_patience=${pat}"
          done
        done
      done
      echo
      echo "# ===== alpha box (alpha was bimodal at BOTH box edges) ====="
      for ds in ${DATASETS}; do
        for amax in 1.0 1.5 3.0; do
          emit "amax$(tag "${amax}")" "${ds}" "--set lambda_dyn=${LAM} --set kot_alpha_max=${amax}"
        done
      done
      echo
      echo "# ===== optimiser ====="
      for ds in ${DATASETS}; do
        for lr in 5.0e-4 1.0e-3 2.0e-3; do
          emit "lr$(tag "${lr}")" "${ds}" "--set lambda_dyn=${LAM} --set lr=${lr}"
        done
      done
      echo
      echo "# ===== Sinkhorn blur ====="
      for ds in ${DATASETS}; do
        for blur in 0.03 0.05 0.1 0.2; do
          emit "blur$(tag "${blur}")" "${ds}" "--set lambda_dyn=${LAM} --set sinkhorn_reg=${blur}"
        done
      done
      echo
      echo "# ===== beta-anchor strength (kot vs kot_noanchor was a null result) ====="
      for ds in ${DATASETS}; do
        for lp in 0.0 0.1 1.0 10.0; do
          emit "lprior$(tag "${lp}")" "${ds}" "--set lambda_dyn=${LAM} --set lambda_prior=${lp}"
        done
      done
      echo
      echo "# ===== velocity gauge (decides what kappa absorbs) ====="
      for ds in ${DATASETS}; do
        for gauge in true false; do
          emit "gauge${gauge}" "${ds}" \
               "--set lambda_dyn=${LAM} --set kot_velocity_gauge_normalize=${gauge}"
        done
      done
      echo
      echo "# ===== batch / align-batch size (BMMC only: PBMC n=5527 is already full-batch) ====="
      for ds in ${DATASETS}; do
        case "${ds}" in *bmmc*) ;; *) continue ;; esac
        for bs in 4096 8192 16384; do
          emit "bs${bs}" "${ds}" "--set lambda_dyn=${LAM} --set batch_size=${bs}"
        done
        for smp in 4096 8192 16384; do
          emit "smp${smp}" "${ds}" "--set lambda_dyn=${LAM} --set sinkhorn_max_points=${smp}"
        done
      done
      ;;

    c)
      # Tier C: curriculum. Both mechanisms already exist in kot.py and are disabled
      # (all zeros). CAUTION on hard phases: phase 2 sets the align weight to 0, and
      # align-only training (kot_nodyn) lands at FOSCTTM 0.36-0.61 with huge seed
      # variance -- so a long phase 1 starts the model inside that bad basin. The
      # ramp (dyn_warmup_epochs, align stays on throughout) is the safer arm.
      echo "# ===== dynamics warmup ramp (align stays on) ====="
      for ds in ${DATASETS}; do
        for warm in 0 50 100 200; do
          emit "warm${warm}" "${ds}" "--set lambda_dyn=${LAM} --set dyn_warmup_epochs=${warm}"
        done
      done
      echo
      echo "# ===== hard phases: P1 Sinkhorn / P2 dynamics / P3 joint @ lr x scale ====="
      for ds in ${DATASETS}; do
        for ph in "50:50:400" "100:100:300" "200:100:200"; do
          IFS=: read -r p1 p2 p3 <<< "${ph}"
          for s in 0.1 0.3; do
            emit "p${p1}-${p2}-${p3}_s$(tag "${s}")" "${ds}" \
                 "--set lambda_dyn=${LAM} --set phase1_epochs=${p1} --set phase2_epochs=${p2} --set phase3_epochs=${p3} --set phase3_lr_scale=${s}"
          done
        done
      done
      echo
      echo "# ===== alpha-head freeze (let phi settle before alpha moves) ====="
      for ds in ${DATASETS}; do
        for gf in 0 50 100; do
          emit "gfreeze${gf}" "${ds}" "--set lambda_dyn=${LAM} --set g_freeze_epochs=${gf}"
        done
      done
      ;;

    *) echo "unknown tier: ${TIER} (expected a, b or c)" >&2; exit 1 ;;
  esac
} > "${OUT}"

n_jobs=$(grep -c '^--' "${OUT}")
n_dirs=$(grep '^--' "${OUT}" | grep -o '\-\-run-dir [^ ]*$' | sort -u | wc -l)
echo "Wrote ${OUT}: ${n_jobs} jobs, ${n_dirs} unique run-dirs"
[ "${n_jobs}" -eq "${n_dirs}" ] || {
  echo "ERROR: run-dir collision -- jobs would overwrite each other" >&2
  grep '^--' "${OUT}" | grep -o '\-\-run-dir [^ ]*$' | sort | uniq -d >&2
  exit 1
}
echo "Submit:  sbatch --export=ALL,JOBS_FILE=${OUT},MAX_PARALLEL=8 slurm/parallel_train.sh"
