#!/usr/bin/env python3
"""Two RNA-coordinate follow-ups on the single best source-representation run.

shared_log1p is already the winner. These two ask whether the missing
library-normalisation derivative in the relay matters:

  panel_log1p_compositional  panel CP10K + log1p, with -x dT/T in the flux
  global_linear              one training-RNA scale; linear u,s; no per-cell dT

Do not expand this across the input screen. Three settings means two new trains.

Usage, after validation has named a winner:
  PYTHONPATH=. python tools/chromatin_rna_coords.py jobs \\
      --winners cache/results/chromatin/kinetic_winners.json
  PYTHONPATH=. python tools/chromatin_rna_coords.py jobs \\
      --run-dir cache/chromatin/runs/r2scr_f_lsi_lam9_seed42
"""
from __future__ import annotations

import argparse
from pathlib import Path

from src.losses.chromatin_laws import GLOBAL_LINEAR, PANEL_LOG1P_COMPOSITIONAL
from tools.chromatin_kinetic_controls import (
    apply_override, load_json, stem_from_winner, train_tokens,
)


def coord_overrides() -> list[dict]:
    return [
        {"tag": "panelcomp", "rna_kinetic_coords": PANEL_LOG1P_COMPOSITIONAL},
        {"tag": "globlin", "rna_kinetic_coords": GLOBAL_LINEAR},
    ]


def load_winner(args: argparse.Namespace) -> dict:
    if args.run_dir is not None:
        run = Path(args.run_dir)
        config = load_json(run / "run_config.json")
        return {"run": run.name, "config": config, "picked_for": "run_dir"}
    if args.winners is None:
        raise ValueError("pass --winners or --run-dir")
    payload = load_json(args.winners)
    winners = payload["winners"] if isinstance(payload, dict) and "winners" in payload else payload
    if not winners:
        raise ValueError("winner file is empty")
    for row in winners:
        if row.get("picked_for") == "alignment":
            return row
    return min(winners, key=lambda row: row["foscttm"])


def rna_coord_jobs(winner: dict) -> list[str]:
    stem = stem_from_winner(winner["run"])
    lines = []
    for override in coord_overrides():
        tag, config = apply_override(winner["config"], override)
        run_dir = f"cache/chromatin/runs/r2rna_{stem}_{tag}_seed42"
        lines.append(" ".join(train_tokens(config, run_dir)))
    return lines


def job_file_text(winner: dict) -> str:
    header = f"""# RNA kinetic coordinates on one source-representation winner.
# Winner: {winner['run']}
#
# shared_log1p is the winner itself. Two new trains:
#   panelcomp  panel CP10K + log1p + compositional dT/T
#   globlin    globally scaled linear u,s
#
# Generated by tools/chromatin_rna_coords.py. Do not hand-write a third
# source representation. Development evaluate: --eval-split val.
#
# Submit from the repo root after the winner's velocity cache exists:
#   while IFS= read -r line; do
#     [[ "$line" =~ ^train ]] || continue
#     name=${{line##*--run-dir cache/chromatin/runs/}}
#     sbatch --job-name="$name" \\
#       --export=ALL,RUN_CMD="PYTHONPATH=. python -u run_kot_chromatin.py $line" \\
#       slurm/train_slurm.sh
#   done < jobs/jobs_chromatin_rna_coords.txt
"""
    return header + "\n" + "\n".join(rna_coord_jobs(winner)) + "\n"


def jobs_main(args: argparse.Namespace) -> int:
    winner = load_winner(args)
    text = job_file_text(winner)
    args.out.write_text(text)
    trains = [line for line in text.splitlines() if line.startswith("train ")]
    print(f"[rna-coords] winner {winner['run']}; wrote {len(trains)} trains to {args.out}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    jobs = sub.add_parser("jobs", help="write the two RNA-coordinate trains")
    jobs.add_argument("--winners", type=Path, default=None,
                      help="kinetic_winners.json; uses the alignment pick")
    jobs.add_argument("--run-dir", type=Path, default=None,
                      help="one completed run to copy identity from")
    jobs.add_argument("--out", type=Path,
                      default=Path("jobs/jobs_chromatin_rna_coords.txt"))
    jobs.set_defaults(func=jobs_main)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "jobs" and args.winners is None and args.run_dir is None:
        raise SystemExit("jobs needs --winners or --run-dir")
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
